version: '2'
services:
    dzzoffice:
        ports:
            - '8010:80'
        image: qhduan/dzzoffice:2.02.1
        restart: always
    document_server:
        ports:
            - '8020:80'
        image: qhduan/documentserver:6.0
        restart: always
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root